version: "3.8"

services:
  armms-keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: armms-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${DB_PASSWORD}

      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_PROXY_HEADERS: xforwarded
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    restart: always
    depends_on:
      - keycloakdb
    ports:
      - 8080:8080
    networks:
      - keycloak-net

  keycloakdb:
    image: postgres:15
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - keycloak-net

networks:
  keycloak-net:
    driver: bridge
